//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class JoyMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/Joy";
        public override string RosMessageName => k_RosMessageName;

        public float[] joy_data;
        public const byte JOYSTICK_LEFT_VERT = 0;
        public const byte JOYSTICK_LEFT_HORIZ = 1;
        public const byte L3 = 2;
        public const byte JOYSTICK_RIGHT_VERT = 3;
        public const byte JOYSTICK_RIGHT_HORIZ = 4;
        public const byte R3 = 5;
        public const byte CROSS_UP = 6;
        public const byte CROSS_DOWN = 7;
        public const byte CROSS_LEFT = 8;
        public const byte CROSS_RIGHT = 9;
        public const byte L1 = 10;
        public const byte L2 = 11;
        public const byte R1 = 12;
        public const byte R2 = 13;
        public const byte A = 14;
        public const byte B = 15;
        public const byte X = 16;
        public const byte Y = 17;
        public const byte SHARE = 18;
        public const byte OPTS = 19;
        public const byte HOME = 20;
        public const byte MAX = 21;

        public JoyMsg()
        {
            this.joy_data = new float[21];
        }

        public JoyMsg(float[] joy_data)
        {
            this.joy_data = joy_data;
        }

        public static JoyMsg Deserialize(MessageDeserializer deserializer) => new JoyMsg(deserializer);

        private JoyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joy_data, sizeof(float), 21);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joy_data);
        }

        public override string ToString()
        {
            return "JoyMsg: " +
            "\njoy_data: " + System.String.Join(", ", joy_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
