//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class SerialHeartbeatMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/SerialHeartbeat";
        public override string RosMessageName => k_RosMessageName;

        //  Set up the QoS to handle disconnection robustly
        public bool beat;

        public SerialHeartbeatMsg()
        {
            this.beat = false;
        }

        public SerialHeartbeatMsg(bool beat)
        {
            this.beat = beat;
        }

        public static SerialHeartbeatMsg Deserialize(MessageDeserializer deserializer) => new SerialHeartbeatMsg(deserializer);

        private SerialHeartbeatMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.beat);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.beat);
        }

        public override string ToString()
        {
            return "SerialHeartbeatMsg: " +
            "\nbeat: " + beat.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
