//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class SerialStatusMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/SerialStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public string message;

        public SerialStatusMsg()
        {
            this.ok = false;
            this.message = "";
        }

        public SerialStatusMsg(bool ok, string message)
        {
            this.ok = ok;
            this.message = message;
        }

        public static SerialStatusMsg Deserialize(MessageDeserializer deserializer) => new SerialStatusMsg(deserializer);

        private SerialStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SerialStatusMsg: " +
            "\nok: " + ok.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
