//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class ServoAnglesMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/ServoAngles";
        public override string RosMessageName => k_RosMessageName;

        public float vert_a;
        public float vert_b;
        public float vert_c;
        public float vert_d;
        public float vert_e;
        public float vert_f;
        public float horiz_a;
        public float horiz_b;
        public float horiz_c;
        public float horiz_d;
        public float horiz_e;
        public float horiz_f;

        public ServoAnglesMsg()
        {
            this.vert_a = 0.0f;
            this.vert_b = 0.0f;
            this.vert_c = 0.0f;
            this.vert_d = 0.0f;
            this.vert_e = 0.0f;
            this.vert_f = 0.0f;
            this.horiz_a = 0.0f;
            this.horiz_b = 0.0f;
            this.horiz_c = 0.0f;
            this.horiz_d = 0.0f;
            this.horiz_e = 0.0f;
            this.horiz_f = 0.0f;
        }

        public ServoAnglesMsg(float vert_a, float vert_b, float vert_c, float vert_d, float vert_e, float vert_f, float horiz_a, float horiz_b, float horiz_c, float horiz_d, float horiz_e, float horiz_f)
        {
            this.vert_a = vert_a;
            this.vert_b = vert_b;
            this.vert_c = vert_c;
            this.vert_d = vert_d;
            this.vert_e = vert_e;
            this.vert_f = vert_f;
            this.horiz_a = horiz_a;
            this.horiz_b = horiz_b;
            this.horiz_c = horiz_c;
            this.horiz_d = horiz_d;
            this.horiz_e = horiz_e;
            this.horiz_f = horiz_f;
        }

        public static ServoAnglesMsg Deserialize(MessageDeserializer deserializer) => new ServoAnglesMsg(deserializer);

        private ServoAnglesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vert_a);
            deserializer.Read(out this.vert_b);
            deserializer.Read(out this.vert_c);
            deserializer.Read(out this.vert_d);
            deserializer.Read(out this.vert_e);
            deserializer.Read(out this.vert_f);
            deserializer.Read(out this.horiz_a);
            deserializer.Read(out this.horiz_b);
            deserializer.Read(out this.horiz_c);
            deserializer.Read(out this.horiz_d);
            deserializer.Read(out this.horiz_e);
            deserializer.Read(out this.horiz_f);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vert_a);
            serializer.Write(this.vert_b);
            serializer.Write(this.vert_c);
            serializer.Write(this.vert_d);
            serializer.Write(this.vert_e);
            serializer.Write(this.vert_f);
            serializer.Write(this.horiz_a);
            serializer.Write(this.horiz_b);
            serializer.Write(this.horiz_c);
            serializer.Write(this.horiz_d);
            serializer.Write(this.horiz_e);
            serializer.Write(this.horiz_f);
        }

        public override string ToString()
        {
            return "ServoAnglesMsg: " +
            "\nvert_a: " + vert_a.ToString() +
            "\nvert_b: " + vert_b.ToString() +
            "\nvert_c: " + vert_c.ToString() +
            "\nvert_d: " + vert_d.ToString() +
            "\nvert_e: " + vert_e.ToString() +
            "\nvert_f: " + vert_f.ToString() +
            "\nhoriz_a: " + horiz_a.ToString() +
            "\nhoriz_b: " + horiz_b.ToString() +
            "\nhoriz_c: " + horiz_c.ToString() +
            "\nhoriz_d: " + horiz_d.ToString() +
            "\nhoriz_e: " + horiz_e.ToString() +
            "\nhoriz_f: " + horiz_f.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
