//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class StepMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/Step";
        public override string RosMessageName => k_RosMessageName;

        public float step;

        public StepMsg()
        {
            this.step = 0.0f;
        }

        public StepMsg(float step)
        {
            this.step = step;
        }

        public static StepMsg Deserialize(MessageDeserializer deserializer) => new StepMsg(deserializer);

        private StepMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.step);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.step);
        }

        public override string ToString()
        {
            return "StepMsg: " +
            "\nstep: " + step.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
